{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if $serviceConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.deploymentLabels" (dict "serviceName" $serviceName "Values" $.Values "Release" $.Release "Chart" $.Chart) | nindent 4 }}
spec:
  replicas: {{ $serviceConfig.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "webrix.serviceSelectorLabels" (dict "serviceName" $serviceName "root" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webrix.podLabels" (dict "serviceName" $serviceName "podLabels" $serviceConfig.podLabels "root" $) | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmaps.yaml") $ | sha256sum }}
        # checksum/configmap: {{ index $.Values.deployments $serviceName "env" | toYaml | sha256sum }}
        {{- with $serviceConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ printf "%s-sa" $serviceName | lower }}
      containers:
        - name: {{ $serviceName | lower }}
          image: "{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag }}"
          {{- if $serviceConfig.image.pullPolicy }}
          imagePullPolicy: {{ $serviceConfig.image.pullPolicy }}
          {{- else if eq ($serviceConfig.image.tag | default "latest") "latest" }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: IfNotPresent
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $serviceConfig.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ printf "%s-config" $serviceName | lower }}
            - secretRef:
                name: {{ printf "%s-secret" $serviceName | lower }}
            {{- if $serviceConfig.secretName }}
            - secretRef:
                name: {{ $serviceConfig.secretName }}
            {{- end }}
            {{- if $serviceConfig.sealedsecret }}
            - secretRef:
                name: {{ $serviceName }}
            {{- end }}
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
          {{- with $serviceConfig.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
