{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if and $serviceConfig.enabled $serviceConfig.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
  {{- with $serviceConfig.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $serviceConfig.ingress.className }}
  ingressClassName: {{ $serviceConfig.ingress.className }}
  {{- end }}
  {{- if $serviceConfig.ingress.tls }}
  tls:
    {{- range $serviceConfig.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: "{{ $serviceConfig.ingress.subdomain }}.{{ $.Values.global.domain.host }}"
      http:
        paths:
        - path: {{ $serviceConfig.ingress.path }}
          pathType: {{ $serviceConfig.ingress.pathType }}
          backend:
            service:
              name: {{ $serviceName | lower }}
              port:
                number: {{ $serviceConfig.service.port }}
{{- end }}
{{- end }}
