{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
spec:
  type: {{ $serviceConfig.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $serviceConfig.service.port }}
      targetPort: {{ $serviceConfig.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ $serviceName }}
{{- end }}
{{- end }}
